import type { DefensiveCallConcept } from './playbookTypes'

export const DEFENSIVE_CALL_CONCEPTS: Partial<Record<string, DefensiveCallConcept>> = {
  four_three_base: {
    front: '4-3',
    coverageShell: 'Base shell (mixed)',
    pressure: '4 rush default',
    runFits: 'Gap sound',
    responsibilities: 'Hook/curl zones, flat support',
    matchupNotes: 'Balanced vs early downs',
  },
  nickel: {
    front: '4-2-5',
    coverageShell: 'Nickel sub package',
    pressure: '4–5 rush',
    runFits: 'Edge spill',
    responsibilities: 'Extra DB vs slot',
    matchupNotes: 'Pass-first downs',
  },
  dime: {
    front: '4-1-6',
    coverageShell: 'Light box',
    pressure: '4 rush',
    runFits: 'Soft edge',
    responsibilities: 'Extra deep help',
    matchupNotes: 'Obvious passing',
  },
  goal_line: {
    front: 'Heavy',
    coverageShell: 'Man / robber',
    pressure: 'Penetrate',
    runFits: 'Wall',
    responsibilities: 'Tight man trail',
    matchupNotes: 'Fade / pick plays',
  },
  cover_2_zone: {
    front: '4-2',
    coverageShell: 'Cover 2 (5 under 2 deep)',
    pressure: '4-man rush default',
    runFits: 'Spill / bounce to force',
    responsibilities: 'Flat corners, hook LBs, safeties half',
    matchupNotes: 'Vulnerable between numbers vs 4 verts',
  },
  cover_3_sky: {
    front: '4-3 / nickel',
    coverageShell: 'Cover 3 sky (SS down)',
    pressure: '4 rush',
    runFits: 'Gap exchange',
    responsibilities: 'Flat zones, curl/hook, deep thirds',
    matchupNotes: 'Hi-lo flats; seams vs seam runners',
  },
  cover_4_quarters: {
    front: '4-2 / 4-3',
    coverageShell: 'Quarters',
    pressure: '4 rush',
    runFits: 'Spill support',
    responsibilities: 'Match carry patterns, invert rules',
    matchupNotes: 'Strong vs verticals; check quick game',
  },
  cover_1_man: {
    front: '4-2',
    coverageShell: '1-high man',
    pressure: '4 rush',
    runFits: 'Man run-through',
    responsibilities: 'Island corners, hole player',
    matchupNotes: 'Pick/rub exposure',
  },
  cover_0_blitz: {
    front: '5–6 rush',
    coverageShell: 'Man zero',
    pressure: 'All-out',
    runFits: 'Penetrate',
    responsibilities: 'Pure man',
    matchupNotes: 'Explosive if block picked up',
  },
  tampa_2: {
    front: '4-3',
    coverageShell: 'Tampa 2 (MIKE drop)',
    pressure: '4 rush',
    runFits: 'Spill',
    responsibilities: 'Deep half + middle hole player',
    matchupNotes: 'Deep middle throws; strong vs vertical seams',
  },
  run_blitz: {
    front: '8-man box look',
    coverageShell: '1-high',
    pressure: 'Aggressive run fit',
    runFits: 'Double teams + spill',
    responsibilities: 'Force inside',
    matchupNotes: 'Play-action over top',
  },
  prevent: {
    front: '3–4 soft',
    coverageShell: '3-deep shell',
    pressure: '3 rush',
    runFits: 'Keep in front',
    responsibilities: 'Deep zones',
    matchupNotes: 'Underneath offense; run creases',
  },
}
