import type { DefensiveCall } from '../footballTypes'

export const DEFENSIVE_PLAYBOOK: DefensiveCall[] = [
  {
    id: 'four_three_base',
    name: '4-3 Base',
    runModifier: 0.35,
    shortPassModifier: 0.45,
    deepPassModifier: -0.2,
    pressureModifier: -0.35,
    turnoverModifier: 0.0,
    bigPlayRiskModifier: -0.02,
    strengthVsInsideRun: 0.35,
    strengthVsOutsideRun: 0.28,
    strengthVsShortPass: 0.35,
    strengthVsDeepPass: 0.25,
    strengthVsScreen: 0.3,
    frontLabel: '4-3',
    shellLabel: 'Base',
    visualTemplateId: 'four_three_base',
  },
  {
    id: 'nickel',
    name: 'Nickel',
    runModifier: -0.15,
    shortPassModifier: 0.35,
    deepPassModifier: -0.35,
    pressureModifier: 0.2,
    turnoverModifier: 0.02,
    bigPlayRiskModifier: 0.04,
    strengthVsInsideRun: 0.1,
    strengthVsOutsideRun: 0.2,
    strengthVsShortPass: 0.45,
    strengthVsDeepPass: 0.3,
    strengthVsScreen: 0.35,
    frontLabel: '4-2-5',
    shellLabel: 'Nickel',
    visualTemplateId: 'nickel',
  },
  {
    id: 'dime',
    name: 'Dime',
    runModifier: -0.55,
    shortPassModifier: 0.15,
    deepPassModifier: 0.45,
    pressureModifier: -0.5,
    turnoverModifier: -0.02,
    bigPlayRiskModifier: -0.1,
    strengthVsInsideRun: -0.15,
    strengthVsOutsideRun: 0.05,
    strengthVsShortPass: 0.35,
    strengthVsDeepPass: 0.55,
    strengthVsScreen: 0.4,
    frontLabel: '4-1-6',
    shellLabel: 'Dime',
    visualTemplateId: 'dime',
  },
  {
    id: 'goal_line',
    name: 'Goal Line',
    runModifier: 1.4,
    shortPassModifier: 0.1,
    deepPassModifier: -1.2,
    pressureModifier: 0.5,
    turnoverModifier: 0.0,
    bigPlayRiskModifier: -0.05,
    strengthVsInsideRun: 0.85,
    strengthVsOutsideRun: 0.5,
    strengthVsShortPass: 0.15,
    strengthVsDeepPass: -0.5,
    strengthVsScreen: 0.0,
    frontLabel: 'Goal line',
    shellLabel: 'Stack',
    visualTemplateId: 'goal_line',
  },
  {
    id: 'cover_2_zone',
    name: 'Cover 2',
    runModifier: 0.4,
    shortPassModifier: 0.9,
    deepPassModifier: -0.8,
    pressureModifier: -0.5,
    turnoverModifier: 0.0,
    bigPlayRiskModifier: -0.05,
    strengthVsInsideRun: 0.3,
    strengthVsOutsideRun: 0.2,
    strengthVsShortPass: 0.6,
    strengthVsDeepPass: 0.5,
    strengthVsScreen: 0.4,
    frontLabel: '4-3',
    shellLabel: 'Cover 2',
    visualTemplateId: 'cover_2_zone',
  },
  {
    id: 'cover_3_sky',
    name: 'Cover 3 Sky',
    runModifier: 0.2,
    shortPassModifier: 0.5,
    deepPassModifier: 0.2,
    pressureModifier: -0.3,
    turnoverModifier: 0.01,
    bigPlayRiskModifier: 0.02,
    strengthVsInsideRun: 0.2,
    strengthVsOutsideRun: 0.3,
    strengthVsShortPass: 0.4,
    strengthVsDeepPass: 0.3,
    strengthVsScreen: 0.35,
    frontLabel: '4-3',
    shellLabel: 'Cover 3 Sky',
    visualTemplateId: 'cover_3_sky',
  },
  {
    id: 'cover_4_quarters',
    name: 'Cover 4 Quarters',
    runModifier: 0.5,
    shortPassModifier: 0.3,
    deepPassModifier: 0.6,
    pressureModifier: -0.6,
    turnoverModifier: -0.02,
    bigPlayRiskModifier: -0.12,
    strengthVsInsideRun: 0.35,
    strengthVsOutsideRun: 0.25,
    strengthVsShortPass: 0.25,
    strengthVsDeepPass: 0.55,
    strengthVsScreen: 0.5,
    frontLabel: '4-3',
    shellLabel: 'Cover 4',
    visualTemplateId: 'cover_4_quarters',
  },
  {
    id: 'cover_1_man',
    name: 'Cover 1 Man',
    runModifier: -0.2,
    shortPassModifier: 0.2,
    deepPassModifier: 0.1,
    pressureModifier: 0.4,
    turnoverModifier: 0.05,
    bigPlayRiskModifier: 0.08,
    strengthVsInsideRun: 0.1,
    strengthVsOutsideRun: 0.15,
    strengthVsShortPass: 0.2,
    strengthVsDeepPass: 0.25,
    strengthVsScreen: 0.1,
    frontLabel: '4-3',
    shellLabel: 'Cover 1',
    visualTemplateId: 'cover_1_man',
  },
  {
    id: 'cover_0_blitz',
    name: 'Cover 0 Blitz',
    runModifier: -0.8,
    shortPassModifier: -0.4,
    deepPassModifier: -1.5,
    pressureModifier: 1.8,
    turnoverModifier: 0.08,
    bigPlayRiskModifier: 0.18,
    strengthVsInsideRun: -0.2,
    strengthVsOutsideRun: -0.3,
    strengthVsShortPass: -0.4,
    strengthVsDeepPass: -0.2,
    strengthVsScreen: -0.6,
    frontLabel: 'Overload',
    shellLabel: 'Cover 0',
    visualTemplateId: 'cover_0_blitz',
  },
  {
    id: 'tampa_2',
    name: 'Tampa 2',
    runModifier: 0.3,
    shortPassModifier: 0.7,
    deepPassModifier: 0.1,
    pressureModifier: -0.35,
    turnoverModifier: 0.02,
    bigPlayRiskModifier: -0.08,
    strengthVsInsideRun: 0.25,
    strengthVsOutsideRun: 0.2,
    strengthVsShortPass: 0.55,
    strengthVsDeepPass: 0.45,
    strengthVsScreen: 0.45,
    frontLabel: '4-3',
    shellLabel: 'Tampa 2',
    visualTemplateId: 'tampa_2',
  },
  {
    id: 'run_blitz',
    name: 'Run Blitz',
    runModifier: 1.6,
    shortPassModifier: -0.2,
    deepPassModifier: -0.9,
    pressureModifier: 0.6,
    turnoverModifier: -0.01,
    bigPlayRiskModifier: 0.05,
    strengthVsInsideRun: 0.9,
    strengthVsOutsideRun: 0.7,
    strengthVsShortPass: -0.3,
    strengthVsDeepPass: -0.4,
    strengthVsScreen: -0.2,
    frontLabel: '4-3',
    shellLabel: 'Run blitz',
    visualTemplateId: 'run_blitz',
  },
  {
    id: 'prevent',
    name: 'Prevent',
    runModifier: -1.0,
    shortPassModifier: -0.6,
    deepPassModifier: 1.4,
    pressureModifier: -1.2,
    turnoverModifier: -0.04,
    bigPlayRiskModifier: -0.15,
    strengthVsInsideRun: -0.5,
    strengthVsOutsideRun: -0.4,
    strengthVsShortPass: -0.3,
    strengthVsDeepPass: 0.8,
    strengthVsScreen: -0.1,
    frontLabel: '3-1-7',
    shellLabel: 'Prevent',
    visualTemplateId: 'prevent',
  },
]
