import type { OffensivePlay } from '../footballTypes'
import { DEFENSE_PLAYBOOK_IDS } from './defenseIds'

/** Fill missing defense ids with 0 for stable resolver keys */
function matchup(p: Partial<Record<string, number>>): OffensivePlay['matchupVsDefense'] {
  const o: Partial<Record<string, number>> = {}
  for (const id of DEFENSE_PLAYBOOK_IDS) {
    o[id] = p[id] ?? 0
  }
  return o
}

export const OFFENSIVE_PLAYBOOK: OffensivePlay[] = [
  {
    id: 'inside_zone',
    name: 'Inside Zone',
    formationId: 'singleback_ace',
    personnel: '11',
    category: 'run',
    baseYards: 3.8,
    variance: 2.8,
    turnoverRisk: 0.018,
    bigPlayChance: 0.05,
    clockCostSeconds: 28,
    tags: ['run', 'inside_zone', 'zone_run'],
    matchupVsDefense: matchup({
      cover_2_zone: -0.4,
      cover_3_sky: 0.2,
      cover_4_quarters: 0.5,
      cover_1_man: -0.2,
      cover_0_blitz: -1.1,
      tampa_2: -0.3,
      nickel: -0.9,
      run_blitz: -1.4,
      goal_line: -1.2,
      prevent: 1.2,
    }),
  },
  {
    id: 'outside_zone',
    name: 'Outside Zone',
    formationId: 'shotgun_trips',
    personnel: '11',
    category: 'run',
    baseYards: 4.2,
    variance: 3.6,
    turnoverRisk: 0.022,
    bigPlayChance: 0.09,
    clockCostSeconds: 26,
    tags: ['run', 'outside_zone'],
    matchupVsDefense: matchup({
      cover_2_zone: 0.3,
      cover_3_sky: 0.6,
      cover_4_quarters: 0.4,
      cover_1_man: 0.2,
      cover_0_blitz: -0.8,
      tampa_2: 0.1,
      nickel: -0.5,
      run_blitz: -1.0,
      goal_line: -0.9,
      prevent: 1.0,
    }),
  },
  {
    id: 'power_o',
    name: 'Power O',
    formationId: 'i_form',
    personnel: '21',
    category: 'run',
    baseYards: 3.2,
    variance: 2.4,
    turnoverRisk: 0.02,
    bigPlayChance: 0.04,
    clockCostSeconds: 30,
    tags: ['run', 'gap', 'inside_zone'],
    matchupVsDefense: matchup({
      cover_2_zone: -0.2,
      cover_3_sky: 0.1,
      cover_4_quarters: 0.3,
      cover_1_man: -0.5,
      cover_0_blitz: -1.0,
      tampa_2: -0.4,
      nickel: -0.7,
      run_blitz: -1.3,
      goal_line: -0.6,
      prevent: 1.4,
    }),
  },
  {
    id: 'quick_slants',
    name: 'Quick Slants',
    formationId: 'shotgun_doubles',
    personnel: '11',
    category: 'pass',
    baseYards: 5.5,
    variance: 2.5,
    turnoverRisk: 0.035,
    bigPlayChance: 0.06,
    clockCostSeconds: 14,
    tags: ['pass', 'quick_game', 'short_pass'],
    matchupVsDefense: matchup({
      cover_2_zone: 0.8,
      cover_3_sky: 0.4,
      cover_4_quarters: -0.2,
      cover_1_man: -0.3,
      cover_0_blitz: -1.8,
      tampa_2: 0.2,
      nickel: -1.2,
      run_blitz: -0.4,
      goal_line: 0.1,
      prevent: -0.6,
    }),
  },
  {
    id: 'stick',
    name: 'Stick',
    formationId: 'shotgun_trips',
    personnel: '11',
    category: 'pass',
    baseYards: 6.0,
    variance: 3.0,
    turnoverRisk: 0.04,
    bigPlayChance: 0.07,
    clockCostSeconds: 16,
    tags: ['pass', 'short_pass', 'quick_game'],
    matchupVsDefense: matchup({
      cover_2_zone: 0.5,
      cover_3_sky: 0.6,
      cover_4_quarters: 0.2,
      cover_1_man: -0.4,
      cover_0_blitz: -1.4,
      tampa_2: 0.5,
      nickel: -1.0,
      run_blitz: -0.3,
      goal_line: -0.2,
      prevent: -0.8,
    }),
  },
  {
    id: 'four_verticals',
    name: 'Four Verticals',
    formationId: 'shotgun_trips',
    personnel: '11',
    category: 'pass',
    baseYards: 12.0,
    variance: 10.0,
    turnoverRisk: 0.1,
    bigPlayChance: 0.26,
    clockCostSeconds: 8,
    tags: ['pass', 'vertical', 'deep_pass'],
    matchupVsDefense: matchup({
      cover_2_zone: 0.4,
      cover_3_sky: 0.9,
      cover_4_quarters: -0.8,
      cover_1_man: 0.2,
      cover_0_blitz: -2.2,
      tampa_2: -0.2,
      nickel: -0.6,
      run_blitz: 0.6,
      goal_line: -1.5,
      prevent: 1.8,
    }),
  },
  {
    id: 'flood',
    name: 'Flood',
    formationId: 'shotgun_trips',
    personnel: '11',
    category: 'pass',
    baseYards: 8.5,
    variance: 5.5,
    turnoverRisk: 0.055,
    bigPlayChance: 0.12,
    clockCostSeconds: 12,
    tags: ['pass', 'medium_pass'],
    matchupVsDefense: matchup({
      cover_2_zone: 0.3,
      cover_3_sky: 0.5,
      cover_4_quarters: 0.1,
      cover_1_man: -0.2,
      cover_0_blitz: -1.6,
      tampa_2: 0.4,
      nickel: -1.1,
      run_blitz: -0.2,
      goal_line: -0.5,
      prevent: 0.9,
    }),
  },
  {
    id: 'mesh',
    name: 'Mesh',
    formationId: 'shotgun_doubles',
    personnel: '11',
    category: 'pass',
    baseYards: 7.0,
    variance: 4.5,
    turnoverRisk: 0.045,
    bigPlayChance: 0.09,
    clockCostSeconds: 14,
    tags: ['pass', 'short_pass', 'movement'],
    matchupVsDefense: matchup({
      cover_2_zone: 0.6,
      cover_3_sky: 0.3,
      cover_4_quarters: 0.0,
      cover_1_man: -0.6,
      cover_0_blitz: -1.5,
      tampa_2: 0.3,
      nickel: -1.0,
      run_blitz: -0.4,
      goal_line: -0.8,
      prevent: -0.4,
    }),
  },
  {
    id: 'screen_pass',
    name: 'Screen Pass',
    formationId: 'shotgun_doubles',
    personnel: '11',
    category: 'pass',
    baseYards: 6.5,
    variance: 5.0,
    turnoverRisk: 0.035,
    bigPlayChance: 0.11,
    clockCostSeconds: 12,
    tags: ['pass', 'screen'],
    matchupVsDefense: matchup({
      cover_2_zone: 0.2,
      cover_3_sky: 0.8,
      cover_4_quarters: 0.6,
      cover_1_man: 0.4,
      cover_0_blitz: -2.0,
      tampa_2: 0.6,
      nickel: -1.4,
      run_blitz: -0.8,
      goal_line: -0.3,
      prevent: -0.2,
    }),
  },
  {
    id: 'play_action_crossers',
    name: 'Play Action Crossers',
    formationId: 'singleback_ace',
    personnel: '12',
    category: 'pass',
    baseYards: 9.0,
    variance: 6.5,
    turnoverRisk: 0.055,
    bigPlayChance: 0.15,
    clockCostSeconds: 15,
    tags: ['pass', 'play_action', 'medium_pass'],
    matchupVsDefense: matchup({
      cover_2_zone: 0.5,
      cover_3_sky: 0.4,
      cover_4_quarters: -0.3,
      cover_1_man: -0.1,
      cover_0_blitz: -1.7,
      tampa_2: 0.2,
      nickel: -1.0,
      run_blitz: -0.5,
      goal_line: -0.6,
      prevent: 0.4,
    }),
  },
  {
    id: 'jet_sweep',
    name: 'Jet Sweep',
    formationId: 'shotgun_trips',
    personnel: '11',
    category: 'run',
    baseYards: 5.0,
    variance: 4.2,
    turnoverRisk: 0.03,
    bigPlayChance: 0.14,
    clockCostSeconds: 20,
    tags: ['run', 'outside_zone', 'trick'],
    matchupVsDefense: matchup({
      cover_2_zone: 0.5,
      cover_3_sky: 0.3,
      cover_4_quarters: 0.2,
      cover_1_man: 0.1,
      cover_0_blitz: -0.6,
      tampa_2: 0.0,
      nickel: -0.4,
      run_blitz: -0.9,
      goal_line: -1.1,
      prevent: 1.1,
    }),
  },
  {
    id: 'field_goal',
    name: 'Field Goal',
    formationId: 'i_form',
    personnel: '10',
    category: 'special',
    baseYards: 0,
    variance: 0,
    turnoverRisk: 0,
    bigPlayChance: 0,
    clockCostSeconds: 8,
    tags: ['special'],
    matchupVsDefense: matchup({}),
  },
  {
    id: 'punt',
    name: 'Punt',
    formationId: 'singleback_ace',
    personnel: '10',
    category: 'special',
    baseYards: 0,
    variance: 0,
    turnoverRisk: 0,
    bigPlayChance: 0,
    clockCostSeconds: 12,
    tags: ['special'],
    matchupVsDefense: matchup({}),
  },
]
