import type { OffensivePlayConcept } from './playbookTypes'

/** Display / analysis metadata keyed by offensive play id */
export const OFFENSIVE_PLAY_CONCEPTS: Partial<Record<string, OffensivePlayConcept>> = {
  inside_zone: {
    formation: '11 personnel, single-back',
    personnel: '1 RB, 1 TE, 3 WR',
    alignment: '2x2 / 3x1',
    assignments: 'Zone steps: covered/uncovered rules',
    routes: [
      { playerRole: 'X', concept: 'Stem + sit vs soft', breakYards: 8, stem: 'Release' },
      { playerRole: 'Z', concept: 'Flat control', breakYards: 3, stem: 'Speed out' },
    ],
    qbDrop: 'under_center_3_step',
    rbPath: 'Press A-gap; read first down lineman',
    blockingScheme: 'zone',
    timingWindows: '0–1.2s mesh with slants',
    progression: 'Alert → single high check → bang footwork',
    strengthsVsShells: 'Soft 2-high; struggles vs loaded boxes',
  },
  outside_zone: {
    formation: '11 / 12',
    personnel: '1 RB, 1–2 TE',
    alignment: 'TE wing',
    assignments: 'Reach / pin / fold',
    routes: [],
    qbDrop: 'under_center_3_step',
    rbPath: 'Wide track, press landmark, bend',
    blockingScheme: 'zone',
    timingWindows: 'Stretch flow',
    progression: 'Cut off TE or bounce',
    strengthsVsShells: 'Over fronts; slower vs spilling LBs',
  },
  power_o: {
    formation: '22 / 12',
    personnel: '2 RB or FB insert',
    alignment: 'Strong I / offset',
    assignments: 'Kick-out, wrap, lead through',
    routes: [],
    qbDrop: 'under_center_3_step',
    rbPath: 'Aim tight, follow puller',
    blockingScheme: 'gap',
    timingWindows: 'Downhill',
    progression: 'One cut',
    strengthsVsShells: 'Light boxes; tight red zone',
  },
  quick_slants: {
    formation: '10 / 11',
    personnel: '3–4 WR',
    alignment: '2x2',
    assignments: 'Slant-flat conflict',
    routes: [
      { playerRole: 'Slot', concept: 'Slant', breakYards: 5, stem: '3-step' },
      { playerRole: 'X', concept: 'Slant', breakYards: 6, stem: '3-step' },
    ],
    qbDrop: 'shotgun_quick',
    rbPath: 'Check-release weak',
    blockingScheme: 'slide',
    timingWindows: '1.0–1.3s',
    progression: 'Hi–lo on hook defender',
    strengthsVsShells: 'Off coverage; pressure vulnerable',
  },
  stick: {
    formation: '11',
    personnel: '3 WR',
    alignment: '3x1',
    assignments: 'Stick / spot / flat',
    routes: [
      { playerRole: 'Y', concept: 'Stick', breakYards: 6, stem: 'Vertical stem' },
    ],
    qbDrop: 'shotgun_quick',
    rbPath: 'Swing control',
    blockingScheme: 'slide',
    timingWindows: '1.2–1.6s',
    progression: 'Flat → stick → hook',
    strengthsVsShells: 'Zone holes; man can trail',
  },
  four_verticals: {
    formation: '10',
    personnel: '4 WR',
    alignment: '2x2',
    assignments: 'Four verts, seam reads',
    routes: [
      { playerRole: 'All WR', concept: 'Go', breakYards: 15, stem: 'Take top' },
    ],
    qbDrop: 'shotgun_5_step',
    rbPath: 'Block / check-release',
    blockingScheme: 'max_protect',
    timingWindows: '2.0s+',
    progression: 'Single high take post; split safeties',
    strengthsVsShells: '1-high; weak vs 2-deep shell',
  },
  flood: {
    formation: '11 / 12',
    personnel: '3 WR 1 TE',
    alignment: '3x1 strong',
    assignments: 'High–low flood flat',
    routes: [
      { playerRole: 'Z', concept: 'Corner', breakYards: 12, stem: '7-step' },
      { playerRole: 'Y', concept: 'Flat', breakYards: 3, stem: 'Speed out' },
    ],
    qbDrop: 'shotgun_5_step',
    rbPath: 'Check flat',
    blockingScheme: 'slide',
    timingWindows: '1.6–2.2s',
    progression: 'Flat → deep out',
    strengthsVsShells: 'Cover 3 corner replace',
  },
  mesh: {
    formation: '11',
    personnel: '3 WR',
    alignment: '2x2',
    assignments: 'Crossing mesh rub',
    routes: [
      { playerRole: 'Slots', concept: 'Mesh sit', breakYards: 5, stem: 'Under' },
    ],
    qbDrop: 'shotgun_quick',
    rbPath: 'Swing',
    blockingScheme: 'slide',
    timingWindows: '1.4–1.8s',
    progression: 'Rub → sit → wheel alert',
    strengthsVsShells: 'Man; zone can wall',
  },
  screen_pass: {
    formation: '11',
    personnel: '3 WR',
    alignment: '3x1',
    assignments: 'OL sell pass set; slip screen',
    routes: [{ playerRole: 'RB', concept: 'Screen', breakYards: -2, stem: 'Delay' }],
    qbDrop: 'shotgun_quick',
    rbPath: 'Screen path',
    blockingScheme: 'screen',
    timingWindows: 'Late pop',
    progression: 'One read',
    strengthsVsShells: 'Aggressive rush; weak vs cloud flat',
  },
  play_action_crossers: {
    formation: '12',
    personnel: '1 RB 2 TE',
    alignment: '2x2 tight',
    assignments: 'PA boot crossers',
    routes: [
      { playerRole: 'Y', concept: 'Cross', breakYards: 12, stem: 'PA sell' },
    ],
    qbDrop: 'play_fake',
    rbPath: 'Fake zone path',
    blockingScheme: 'play_action',
    timingWindows: '2.0s',
    progression: 'Cross → flat → checkdown',
    strengthsVsShells: 'Aggressive second level',
  },
  jet_sweep: {
    formation: '11',
    personnel: '4 WR / motion WR',
    alignment: 'Jet motion',
    assignments: 'Orbit / arc block',
    routes: [],
    qbDrop: 'shotgun_quick',
    rbPath: 'Jet sweep track',
    blockingScheme: 'zone',
    timingWindows: 'Fast edge',
    progression: 'Mesh handoff',
    strengthsVsShells: 'Wide alignment; edge force',
  },
}
