export const PLAY_FEEL = {
  playbackTimeScale: 0.34,
  substepDt: 1 / 60,
  maxFrameDtSeconds: 0.25,
  readableRunMinSeconds: 3.2,
  readableRunMaxSeconds: 7.5,
  player: {
    globalSpeedMultiplier: 0.68,
    controlledSpeedMultiplier: 1.05,
    controlledAccelerationMultiplier: 1.1,
    lateralControlYards: 9,
    forwardControlYards: 6,
    maxFieldY: 26,
    minFieldX: 1,
    maxFieldX: 99,
  },
  contact: {
    engageRadius: 1.25,
    tackleRadius: 0.62,
    tackleSecureRadius: 0.42,
    blockSlowMultiplier: 0.42,
    shedBaseSeconds: 0.95,
  },
  pass: {
    qbAutoThrowSeconds: 0.74,
    minFlightSeconds: 0.42,
    maxFlightSeconds: 0.78,
    flightSecondsPerYard: 0.065,
    catchRadius: 1.18,
    swatRadius: 1.45,
    interceptRadius: 1.05,
  },
  action: {
    tackleLungeSeconds: 0.28,
    tackleLungeBoost: 2.3,
    jukeBoostY: 3.0,
    diveBoostX: 2.0,
    shedBoostSeconds: 0.35,
  },
} as const
